[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/logs/crud/app.log
    Tag               app.*
    Parser            json_parser
    Refresh_Interval  5
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On


[OUTPUT]
    Name              loki
    Match             *
    Host              34.78.29.222
    Port              3100
    Labels            job=app,env=dev
    Remove_keys       timestamp

